[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "forge-std/=lib/hyperspeed-bridge-fork/solidity/lib/forge-std/src/",
    "hyperspeed-bridge-fork/=lib/hyperspeed-bridge-fork/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
